### ISSUE TITLE
error after latest update

### ISSUE THREAD

**Issue by kuradi** [Olen/home-assistant-openplantbook#13]
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 18:19:04 (1 occurrences)
Last logged: 18:19:04

Setup failed for custom integration 'openplantbook': Unable to import component: cannot import name 'async_track_time_int1erval' from 'homeassistant.helpers.event' (/usr/src/homeassistant/homeassistant/helpers/event.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/openplantbook/__init__.py", line 51, in <module>
    from .uploader import (
  File "/config/custom_components/openplantbook/uploader.py", line 16, in <module>
    from homeassistant.helpers.event import async_track_time_int1erval, async_call_later
ImportError: cannot import name 'async_track_time_int1erval' from 'homeassistant.helpers.event' (/usr/src/homeassistant/homeassistant/helpers/event.py)

**Comment by slaxor505** [comment]
Thanks for jumping on Beta so quickly. Apologies for the hiccup.  I fixed typo in the code and submitted new PR https://github.com/Olen/home-assistant-openplantbook/pull/15

**Comment by Olen** [comment]
Fixed with #15
